"""Add privacy fields to User

Revision ID: 046464c9fa3e
Revises: 574b9cd25b5f
Create Date: 2026-05-25 15:45:55.309191
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '046464c9fa3e'
down_revision = '574b9cd25b5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check comment_likes
    comment_likes_cols = [c['name'] for c in inspector.get_columns('comment_likes')]
    if 'reaction_type' not in comment_likes_cols:
        op.add_column('comment_likes', sa.Column('reaction_type', sa.Enum('like', 'love', 'haha', 'wow', 'sad', 'angry', name='reaction_type', native_enum=False), server_default='like', nullable=False))

    # Check likes
    likes_cols = [c['name'] for c in inspector.get_columns('likes')]
    if 'reaction_type' not in likes_cols:
        op.add_column('likes', sa.Column('reaction_type', sa.Enum('like', 'love', 'haha', 'wow', 'sad', 'angry', name='reaction_type', native_enum=False), server_default='like', nullable=False))

    # Check posts indices
    posts_indices = [idx['name'] for idx in inspector.get_indexes('posts')]
    if 'idx_posts_content_fts' not in posts_indices:
        op.create_index('idx_posts_content_fts', 'posts', [sa.literal_column("to_tsvector('simple', content)")], unique=False, postgresql_using='gin')

    # Check posts columns
    posts_cols = [c['name'] for c in inspector.get_columns('posts')]
    if 'tagged_users' in posts_cols:
        op.drop_column('posts', 'tagged_users')

    # Check users columns
    users_cols = [c['name'] for c in inspector.get_columns('users')]
    if 'contact_privacy' not in users_cols:
        op.add_column('users', sa.Column('contact_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    if 'email_privacy' not in users_cols:
        op.add_column('users', sa.Column('email_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    if 'location_privacy' not in users_cols:
        op.add_column('users', sa.Column('location_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_privacy')
    op.drop_column('users', 'email_privacy')
    op.drop_column('users', 'contact_privacy')
    op.add_column('posts', sa.Column('tagged_users', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_posts_content_fts', table_name='posts', postgresql_using='gin')
    op.drop_column('likes', 'reaction_type')
    op.drop_column('comment_likes', 'reaction_type')
    # ### end Alembic commands ###
