"""add comment likes

Revision ID: 09e9b72d623a
Revises: 79d8ced5586e
Create Date: 2026-04-25 16:30:23.769377
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '09e9b72d623a'
down_revision = '79d8ced5586e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('idx_comment_likes_user_id', 'comment_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comment_likes_user_id', table_name='comment_likes')
    op.drop_table('comment_likes')
    # ### end Alembic commands ###
