"""add feeling and tagged_users to post

Revision ID: 106e360d7499
Revises: a3f1c8e92b4d
Create Date: 2026-05-21 03:01:23.992929
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '106e360d7499'
down_revision = 'a3f1c8e92b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Kiểm tra các cột trong bảng posts trước khi thêm để tránh lỗi DuplicateColumn
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    post_columns = [c['name'] for c in inspector.get_columns('posts')]
    if 'feeling' not in post_columns:
        op.add_column('posts', sa.Column('feeling', sa.Text(), nullable=True))
    if 'tagged_users' not in post_columns:
        op.add_column('posts', sa.Column('tagged_users', sa.JSON(), nullable=True))

    # Kiểm tra sự tồn tại của cột trước khi drop để tránh lỗi hỏng transaction (InFailedSqlTransaction) trong PostgreSQL
    user_columns = [c['name'] for c in inspector.get_columns('users')]
    for col in ['studio', 'headline', 'website']:
        if col in user_columns:
            op.drop_column('users', col)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('studio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'tagged_users')
    op.drop_column('posts', 'feeling')
    # ### end Alembic commands ###
