"""add feeling and tagged_users to post

Revision ID: 106e360d7499
Revises: a3f1c8e92b4d
Create Date: 2026-05-21 03:01:23.992929
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '106e360d7499'
down_revision = 'a3f1c8e92b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('feeling', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('tagged_users', sa.JSON(), nullable=True))
    op.drop_column('users', 'studio')
    op.drop_column('users', 'headline')
    op.drop_column('users', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('studio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'tagged_users')
    op.drop_column('posts', 'feeling')
    # ### end Alembic commands ###
