"""Add extra post fields

Revision ID: 574b9cd25b5f
Revises: 5ebc086a99d8
Create Date: 2026-05-22 03:12:07.877071
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '574b9cd25b5f'
down_revision = 'c2f944c0d241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'post_tags' not in tables:
        op.create_table('post_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('post_id', 'user_id', name='uq_post_tags_post_user')
        )
        
    posts_cols = [c['name'] for c in inspector.get_columns('posts')]
    if 'feeling' not in posts_cols:
        op.add_column('posts', sa.Column('feeling', sa.Text(), nullable=True))
    if 'gif_url' not in posts_cols:
        op.add_column('posts', sa.Column('gif_url', sa.Text(), nullable=True))
    if 'location_name' not in posts_cols:
        op.add_column('posts', sa.Column('location_name', sa.Text(), nullable=True))
    if 'location_lat' not in posts_cols:
        op.add_column('posts', sa.Column('location_lat', sa.Float(), nullable=True))
    if 'location_lng' not in posts_cols:
        op.add_column('posts', sa.Column('location_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # ### commands auto generated by Alembic - please adjust! ###
    posts_cols = [c['name'] for c in inspector.get_columns('posts')]
    if 'location_lng' in posts_cols:
        op.drop_column('posts', 'location_lng')
    if 'location_lat' in posts_cols:
        op.drop_column('posts', 'location_lat')
    if 'location_name' in posts_cols:
        op.drop_column('posts', 'location_name')
    if 'gif_url' in posts_cols:
        op.drop_column('posts', 'gif_url')
    if 'feeling' in posts_cols:
        op.drop_column('posts', 'feeling')
        
    tables = inspector.get_table_names()
    if 'post_tags' in tables:
        op.drop_table('post_tags')
    # ### end Alembic commands ###
