"""Add extra post fields

Revision ID: 574b9cd25b5f
Revises: 5ebc086a99d8
Create Date: 2026-05-22 03:12:07.877071
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '574b9cd25b5f'
down_revision = '106e360d7499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_tags_post_user')
    )
    op.add_column('posts', sa.Column('feeling', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('gif_url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('location_name', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('location_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'location_lng')
    op.drop_column('posts', 'location_lat')
    op.drop_column('posts', 'location_name')
    op.drop_column('posts', 'gif_url')
    op.drop_column('posts', 'feeling')
    op.drop_table('post_tags')
    # ### end Alembic commands ###
