"""Add reaction_type

Revision ID: 5ebc086a99d8
Revises: 7f718b20cd84
Create Date: 2026-05-20 15:55:17.452440
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5ebc086a99d8'
down_revision = '7f718b20cd84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_likes', sa.Column('reaction_type', sa.Enum('like', 'love', 'haha', 'wow', 'sad', 'angry', name='reaction_type', native_enum=False), server_default='like', nullable=False))
    op.add_column('likes', sa.Column('reaction_type', sa.Enum('like', 'love', 'haha', 'wow', 'sad', 'angry', name='reaction_type', native_enum=False), server_default='like', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'reaction_type')
    op.drop_column('comment_likes', 'reaction_type')
    # ### end Alembic commands ###
