"""Add profile fields to user

Revision ID: 7bc8f5d8f747
Revises: 0006_add_reported_count_to_posts
Create Date: 2026-04-11 00:00:11.804571
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7bc8f5d8f747'
down_revision = '0006_add_reported_count_to_posts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_sessions_token_id_key'), 'refresh_sessions', type_='unique')
    op.drop_index(op.f('ix_refresh_sessions_token_id'), table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_token_id'), 'refresh_sessions', ['token_id'], unique=True)
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_refresh_sessions_token_id'), table_name='refresh_sessions')
    op.create_index(op.f('ix_refresh_sessions_token_id'), 'refresh_sessions', ['token_id'], unique=False)
    op.create_unique_constraint(op.f('refresh_sessions_token_id_key'), 'refresh_sessions', ['token_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
