"""add_post_fts_index

Revision ID: 7f718b20cd84
Revises: f4a6c2b9d001
Create Date: 2026-05-14 10:53:05.819646
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7f718b20cd84'
down_revision = 'f4a6c2b9d001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_posts_content_fts', 'posts', [sa.literal_column("to_tsvector('simple', 'content')")], unique=False, postgresql_using='gin')
    op.drop_column('users', 'website')
    op.drop_column('users', 'studio')
    op.drop_column('users', 'headline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headline', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('studio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('idx_posts_content_fts', table_name='posts', postgresql_using='gin')
    # ### end Alembic commands ###
