"""Add profile fields

Revision ID: 8a8aee65771e
Revises: 09e9b72d623a
Create Date: 2026-04-26 18:02:52.814114
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8a8aee65771e'
down_revision = '09e9b72d623a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('headline', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('studio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('users', 'studio')
    op.drop_column('users', 'headline')
    # ### end Alembic commands ###
