"""Add privacy settings

Revision ID: 9563cc2825d1
Revises: 106e360d7499
Create Date: 2026-05-23 20:09:32.875708
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9563cc2825d1'
down_revision = '106e360d7499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    op.add_column('users', sa.Column('email_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    op.add_column('users', sa.Column('location_privacy', sa.Enum('public', 'followersonly', 'custom', 'onlyme', name='visibility_level', native_enum=False), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_privacy')
    op.drop_column('users', 'email_privacy')
    op.drop_column('users', 'contact_privacy')
    # ### end Alembic commands ###
