"""Add privacy columns

Revision ID: c2f944c0d241
Revises: 9563cc2825d1
Create Date: 2026-05-23 20:45:37.049965
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c2f944c0d241'
down_revision = '9563cc2825d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
