"""add_group_avatar

Revision ID: c5175e175ad2
Revises: ee9b53c9c9d6
Create Date: 2026-06-01 21:13:56.075814
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c5175e175ad2'
down_revision = 'ee9b53c9c9d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'avatar_url')
    # ### end Alembic commands ###
