"""Add shared_post_id to posts

Revision ID: ee9b53c9c9d6
Revises: e4b37d45f32b
Create Date: 2026-05-27 15:02:32.753035
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ee9b53c9c9d6'
down_revision = 'e4b37d45f32b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('shared_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['shared_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'shared_post_id')
    # ### end Alembic commands ###
